apiVersion: v1
kind: Service
metadata:
  name: notes-web-service
  labels:
    app: notes-web
spec:
  type: NodePort
  selector:
    app: notes-web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
